services:
  catalogdb:
    build:
      context: .
      dockerfile: Services/Catalog.API/Dockerfile.catalogdb
    image: catalog-db:1.0
    container_name: catalogdb
    environment:
      - POSTGRES_DB=catalogdb
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    volumes:
      - catalog-db:/var/lib/postgresql/data/

  catalogapi:
    build:
      context: .
      dockerfile: Services/Catalog.API/Dockerfile.catalogapi
    image: catalog-api:1.0
    container_name: catalogapi
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENV}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${ASPNETCORE_CERTIFICATES_PASSWORD}
      - ConnectionStrings__Database=host=catalogdb;port=5432;database=catalogdb;username=${POSTGRES_USER};password=${POSTGRES_PASSWORD}
    restart: always
    ports:
      - 6000:8080
      - 6060:8081
    volumes:
      - ~/.aspnet/https/aspnetapp.pfx:/https/aspnetapp.pfx:ro
    depends_on:
      catalogdb:
        condition: service_healthy

  basketdb:
    build:
      context: .
      dockerfile: Services/Basket.API/Dockerfile.basketdb
    image: basket-db:1.0
    container_name: basketdb
    environment:
      - POSTGRES_DB=basketdb
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    volumes:
      - basket-db:/var/lib/postgresql/data/

  basketcache:
    build:
      context: .
      dockerfile: Services/Basket.API/Dockerfile.basketcache
    image: basket-cache:1.0
    container_name: basketcache
    environment:
      - REDIS_ARGS=--requirepass ${REDIS_PASSWORD}
    restart: always
    volumes:
      - basket-cache:/data/

  basketapi:
    build:
      context: .
      dockerfile: Services/Basket.API/Dockerfile.basketapi
    image: basket-api:1.0
    container_name: basketapi
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENV}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${ASPNETCORE_CERTIFICATES_PASSWORD}
      - ConnectionStrings__Database=host=basketdb;port=5432;database=basketdb;username=${POSTGRES_USER};password=${POSTGRES_PASSWORD}
      - ConnectionStrings__Cache=basketcache:6379,password=${REDIS_PASSWORD}
      - GrpcSettings__DiscountUrl=https://discountgrpc:6062
    restart: always
    ports:
      - 6001:8080
      - 6061:8081
    volumes:
      - ~/.aspnet/https/aspnetapp.pfx:/https/aspnetapp.pfx:ro
    depends_on:
      basketdb:
        condition: service_healthy
      basketcache:
        condition: service_healthy
      discountgrpc:
        condition: service_healthy

  discountgrpc:
    build:
      context: .
      dockerfile: Services/Discount.Grpc/Dockerfile.discountgrpc
    image: discount-grpc:1.0
    container_name: discountgrpc
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENV}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${ASPNETCORE_CERTIFICATES_PASSWORD}
    restart: always
    ports:
      - 6002:6002
      - 6062:6062
    volumes:
      - ~/.aspnet/https/aspnetapp.pfx:/https/aspnetapp.pfx:ro

  orderingapi:
    build:
      context: .
      dockerfile: Services/Ordering.API/Dockerfile.orderingapi
    image: ordering-api:1.0
    container_name: orderingapi
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENV}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${ASPNETCORE_CERTIFICATES_PASSWORD}
    restart: always
    ports:
      - 6003:8080
      - 6063:8081
    volumes:
      - ~/.aspnet/https/aspnetapp.pfx:/https/aspnetapp.pfx:ro

volumes:
  basket-db:
  basket-cache:
  catalog-db:
