services:
  catalogdb:
    image: postgres

  catalogapi:
    build:
      context: .
      dockerfile: Services/Catalog.API/Dockerfile
    image: catalog-api
    depends_on:
      - catalogdb

  basketdb:
    image: postgres

  basketcache:
    image: redis

  basketapi:
    build:
      context: .
      dockerfile: Services/Basket.API/Dockerfile
    image: basket-api
    depends_on:
      - basketdb
      - basketcache

  discountgrpc:
    build:
      context: .
      dockerfile: Services/Discount.Grpc/Dockerfile
    image: discount-grpc

volumes:
  basket-db:
  basket-cache:
  catalog-db:
