services:
  catalogdb:
    container_name: catalogdb
    environment:
      - POSTGRES_DB=catalogdb
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    volumes:
      - catalog-db:/var/lib/postgresql/data/

  catalogapi:
    container_name: catalogapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${ASPNETCORE_CERTIFICATES_PASSWORD}
      - ConnectionStrings__Database=host=catalogdb;port=5432;database=catalogdb;username=${POSTGRES_USER};password=${POSTGRES_PASSWORD}
    restart: always
    ports:
      - 6000:8080
      - 6060:8081
    volumes:
      - ~/.aspnet/https/:/https:ro

  basketdb:
    container_name: basketdb
    environment:
      - POSTGRES_DB=basketdb
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    volumes:
      - basket-db:/var/lib/postgresql/data/

  basketcache:
    container_name: basketcache
    environment:
      - REDIS_ARGS=--requirepass ${REDIS_PASSWORD}
    restart: always
    volumes:
      - basket-cache:/data/

  basketapi:
    container_name: basketapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${ASPNETCORE_CERTIFICATES_PASSWORD}
      - ConnectionStrings__Database=host=basketdb;port=5432;database=basketdb;username=${POSTGRES_USER};password=${POSTGRES_PASSWORD}
      - ConnectionStrings__Cache=basketcache:6379,password=${REDIS_PASSWORD}
    restart: always
    ports:
      - 6001:8080
      - 6061:8081
    volumes:
      - ~/.aspnet/https/:/https:ro

  discountgrpc:
    container_name: discountgrpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${ASPNETCORE_CERTIFICATES_PASSWORD}
    restart: always
    expose:
      - 6002:8080
      - 6062:8081
    ports:
      - 6002:8080
      - 6062:8081
    volumes:
      - ~/.aspnet/https/:/https:ro
