services:
  catalogdb:
    image: postgres

  catalogapi:
    build:
      context: .
      dockerfile: Services/Catalog.API/Dockerfile
    image: catalog-api
    depends_on:
      catalogdb:
        condition: service_healthy

  basketdb:
    image: postgres

  basketcache:
    image: redis

  basketapi:
    build:
      context: .
      dockerfile: Services/Basket.API/Dockerfile
    image: basket-api
    depends_on:
      basketdb:
        condition: service_healthy
      basketcache:
        condition: service_healthy
      discountgrpc:
        condition: service_healthy

  discountgrpc:
    build:
      context: .
      dockerfile: Services/Discount.Grpc/Dockerfile
    image: discount-grpc

  orderingapi:
    build:
      context: .
      dockerfile: Services/Ordering.API/Dockerfile
    image: ordering-api

volumes:
  basket-db:
  basket-cache:
  catalog-db:
