services:
  discountgrpc:
    container_name: discountgrpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${ASPNETCORE_CERTIFICATES_PASSWORD}
    restart: always
    ports:
      - 6002:8080
      - 6062:8081
    volumes:
      - ~/.aspnet/https/:/https:ro
