services:
  basketdb:
    container_name: basketdb
    environment:
      - POSTGRES_DB=basketdb
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    ports:
      - 5431:5432
    volumes:
      - basket-db:/var/lib/postgresql/data/

  basketcache:
    container_name: basketcache
    environment:
      - REDIS_ARGS=--requirepass ${REDIS_PASSWORD}
    restart: always
    ports:
      - 6379:6379
    volumes:
      - basket-cache:/data/
