services:
  catalogdb:
    container_name: catalogdb
    environment:
      - POSTGRES_DB=catalogdb
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    ports:
      - 5430:5432
    volumes:
      - catalog-db:/var/lib/postgresql/data/
