services:
  catalogdb:
    image: postgres

  catalog:
    build:
      context: ../../
      dockerfile: Services/Catalog.API/Dockerfile
    image: catalog-api
    depends_on:
      - catalogdb

volumes:
  catalogdb:
