// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eCommerceApp.DiscountGrpc.Data;

#nullable disable

namespace Discount.Grpc.Migrations
{
    [DbContext(typeof(DiscountContext))]
    [Migration("20240925095250_NewMigration")]
    partial class NewMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("eCommerceApp.Discount.Grpc.Models.Coupon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("206bb5a8-a2a9-4e6b-8a12-74737be21aad"),
                            Amount = 50m,
                            Description = "Iphone discount",
                            ProductId = new Guid("16676e61-9c66-4f5d-9ba2-a775b6d326d1"),
                            ProductName = "Iphone X"
                        },
                        new
                        {
                            Id = new Guid("9d86d345-6c10-4483-9368-428f3ce5667d"),
                            Amount = 100m,
                            Description = "Samsung discount",
                            ProductId = new Guid("c63d2f83-f353-42e1-a07f-8be599379a32"),
                            ProductName = "Samsung S21"
                        },
                        new
                        {
                            Id = new Guid("97a5ccb3-714e-4942-bd51-6e0a0ceac7ea"),
                            Amount = 70m,
                            Description = "Google Pixel discount",
                            ProductId = new Guid("1ad04d68-4871-47af-a2bb-7f6864cefc08"),
                            ProductName = "Google Pixel 5"
                        },
                        new
                        {
                            Id = new Guid("9c9d97c3-7135-41ec-8acf-6ba72d0636e2"),
                            Amount = 60m,
                            Description = "OnePlus discount",
                            ProductId = new Guid("70098a3c-6917-49b9-910c-8078cd7fdf21"),
                            ProductName = "OnePlus 9"
                        },
                        new
                        {
                            Id = new Guid("964c1485-e5fd-45b3-8fe8-15f1a8d7149a"),
                            Amount = 15m,
                            Description = "Xiami discount",
                            ProductId = new Guid("6967eb61-fb97-4791-a808-7c3c0208cd70"),
                            ProductName = "Xiaomi Mi 11"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
