// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eCommerceApp.DiscountGrpc.Data;

#nullable disable

namespace Discount.Grpc.Migrations
{
    [DbContext(typeof(DiscountContext))]
    [Migration("20240921063235_NewMigrations")]
    partial class NewMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("eCommerceApp.Discount.Grpc.Models.Coupon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fe579b97-9006-4bde-82f5-c5676e20d6ea"),
                            Amount = 50m,
                            Description = "Iphone discount",
                            ProductId = new Guid("16676e61-9c66-4f5d-9ba2-a775b6d326d1"),
                            ProductName = "Iphone X"
                        },
                        new
                        {
                            Id = new Guid("05da7b19-44ff-4441-8097-1f75cc4475df"),
                            Amount = 100m,
                            Description = "Samsung discount",
                            ProductId = new Guid("c63d2f83-f353-42e1-a07f-8be599379a32"),
                            ProductName = "Samsung S21"
                        },
                        new
                        {
                            Id = new Guid("f2e3b9ec-1030-4de0-a76f-e93f01782749"),
                            Amount = 70m,
                            Description = "Google Pixel discount",
                            ProductId = new Guid("1ad04d68-4871-47af-a2bb-7f6864cefc08"),
                            ProductName = "Google Pixel 5"
                        },
                        new
                        {
                            Id = new Guid("e4116eba-0f9f-42f3-8de2-93af39a760aa"),
                            Amount = 60m,
                            Description = "OnePlus discount",
                            ProductId = new Guid("70098a3c-6917-49b9-910c-8078cd7fdf21"),
                            ProductName = "OnePlus 9"
                        },
                        new
                        {
                            Id = new Guid("6a3f64ad-a605-4cb2-85c7-63c9facb1d8d"),
                            Amount = 15m,
                            Description = "Xiami discount",
                            ProductId = new Guid("6967eb61-fb97-4791-a808-7c3c0208cd70"),
                            ProductName = "Xiaomi Mi 11"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
