// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eCommerceApp.DiscountGrpc.Data;

#nullable disable

namespace Discount.Grpc.Migrations
{
    [DbContext(typeof(DiscountContext))]
    [Migration("20240919184454_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("eCommerceApp.Discount.Grpc.Models.Coupon", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("66447ae7-0d70-4f6f-ae5b-d31044ec789a"),
                            Amount = 70m,
                            Description = "Google Pixel discount",
                            ProductName = "Google Pixel 5"
                        },
                        new
                        {
                            ProductId = new Guid("9e58b473-9679-4c48-bf72-6a56ff2a0a22"),
                            Amount = 80m,
                            Description = "OnePlus discount",
                            ProductName = "OnePlus 9"
                        },
                        new
                        {
                            ProductId = new Guid("5b52a704-1c17-4d5a-90e3-3d2f787472f7"),
                            Amount = 30m,
                            Description = "Xiaomi discount",
                            ProductName = "Xiaomi Mi 11"
                        },
                        new
                        {
                            ProductId = new Guid("feb6d5ae-8a58-4a64-bf1c-bc788021ae96"),
                            Amount = 50m,
                            Description = "Iphone discount",
                            ProductName = "Iphone X"
                        },
                        new
                        {
                            ProductId = new Guid("eb354dda-b488-4b73-8d81-f4eafbc17cf7"),
                            Amount = 30m,
                            Description = "Xiaomi discount",
                            ProductName = "Xiaomi Mi 11"
                        },
                        new
                        {
                            ProductId = new Guid("18bbc613-6d2d-4312-88a3-2468dff9fb64"),
                            Amount = 50m,
                            Description = "Iphone discount",
                            ProductName = "Iphone X"
                        },
                        new
                        {
                            ProductId = new Guid("c6e740c3-acef-4cba-8fac-0e64b236e71e"),
                            Amount = 70m,
                            Description = "Google Pixel discount",
                            ProductName = "Google Pixel 5"
                        },
                        new
                        {
                            ProductId = new Guid("558dbb83-6eae-4d05-bfe3-7518ab307673"),
                            Amount = 70m,
                            Description = "Google Pixel discount",
                            ProductName = "Google Pixel 5"
                        },
                        new
                        {
                            ProductId = new Guid("df65e387-8e1d-4185-879f-17fc1bb95711"),
                            Amount = 30m,
                            Description = "Xiaomi discount",
                            ProductName = "Xiaomi Mi 11"
                        },
                        new
                        {
                            ProductId = new Guid("95d4bc92-f6be-4634-8c5e-39f456866b3e"),
                            Amount = 100m,
                            Description = "Samsung discount",
                            ProductName = "Samsung S21"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
