// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eCommerceApp.DiscountGrpc.Data;

#nullable disable

namespace Discount.Grpc.Migrations
{
    [DbContext(typeof(DiscountContext))]
    partial class DiscountContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("eCommerceApp.Discount.Grpc.Models.Coupon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("72fa5226-3e79-4cf8-b426-8f3f6eef2dff"),
                            Amount = 50m,
                            Description = "Iphone discount",
                            ProductId = new Guid("16676e61-9c66-4f5d-9ba2-a775b6d326d1"),
                            ProductName = "Iphone X"
                        },
                        new
                        {
                            Id = new Guid("7a4e79db-591f-4f28-9173-e6e4b2c2843e"),
                            Amount = 100m,
                            Description = "Samsung discount",
                            ProductId = new Guid("c63d2f83-f353-42e1-a07f-8be599379a32"),
                            ProductName = "Samsung S21"
                        },
                        new
                        {
                            Id = new Guid("738efc5b-e91d-49c0-bbc0-828b2e972709"),
                            Amount = 70m,
                            Description = "Google Pixel discount",
                            ProductId = new Guid("1ad04d68-4871-47af-a2bb-7f6864cefc08"),
                            ProductName = "Google Pixel 5"
                        },
                        new
                        {
                            Id = new Guid("d179434d-0d55-47d4-9bc0-813ae707ddba"),
                            Amount = 60m,
                            Description = "OnePlus discount",
                            ProductId = new Guid("70098a3c-6917-49b9-910c-8078cd7fdf21"),
                            ProductName = "OnePlus 9"
                        },
                        new
                        {
                            Id = new Guid("31c0e677-325f-4611-ae0f-fc22828a542b"),
                            Amount = 15m,
                            Description = "Xiami discount",
                            ProductId = new Guid("6967eb61-fb97-4791-a808-7c3c0208cd70"),
                            ProductName = "Xiaomi Mi 11"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
